### ISSUE TITLE
spatial join 

### ISSUE THREAD

**Issue by djfan** [djfan/why_yellow_taxi#2]
- [x] test in dumbo ☕️ 

- [x] pandas.DataFrame -> pyspark.DataFrame

- [x] filter: datetime/day of week

- [x] visualization eg. networkx

**Comment by cx495** [comment]
if necessary:

- [x] radius of buffer (adjustment)

**Comment by djfan** [comment]
about filtering time/day of week:
[weekend and late night service](https://www.dropbox.com/s/2pzvfyicyjp3j6v/Screenshot%202017-04-16%2022.57.30.png?dl=0)

PS: will be quite complicated but challengeable
